/* eslint-disable no-magic-numbers */
export const HTTP_ERRORS = {
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  DUPLICATE: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
}
export const AVERAGE_PASSWORD_HASHING_DURATION = 1000
